Enable keyword arguments for particle methods (#2660)
> [!NOTE]
> ~~This PR requires some changes to AdvancedPS.
https://github.com/TuringLang/AdvancedPS.jl/pull/118~~ This is merged
>
> ~~It also needs the following Libtask patch:
https://github.com/TuringLang/Libtask.jl/pull/198~~ This is merged
>
> ~~This PR also lacks tests; some should be added.~~ Tests added.

This PR allows models with keyword arguments to be run with SMC / PG.

Example:

```julia
julia> using Turing

julia> @model function m(y; n=0)
           x ~ Normal(n)
           y ~ Normal(x)
       end
m (generic function with 2 methods)

julia> mean(sample(m(5.0), PG(20), 1000))
[...]
ERROR: Models with keyword arguments need special treatment to be used with particle methods. Please run:

    using Libtask; Libtask.@might_produce(m)

before sampling from this model with particle methods.

Stacktrace:
[...]

julia> using Libtask; Libtask.@might_produce(m)

julia> mean(sample(m(5.0), PG(20), 1000))
Sampling 100%|███████████████████████████████████████████████████████████████████| Time: 0:00:05
Mean

  parameters      mean
      Symbol   Float64

           x    2.7182



julia> mean(sample(m(5.0; n=10.0), PG(20), 1000))
Sampling 100%|███████████████████████████████████████████████████████████████████| Time: 0:00:04
Mean

  parameters      mean
      Symbol   Float64

           x    7.4854
```

Closes #2007.